### ISSUE TITLE
侧边栏宽度会随着浏览器高度变化

### ISSUE THREAD

**Issue by happyhuizai** [zhongqiang1839/nuxt-blog#1]
![w](https://user-images.githubusercontent.com/29218617/58316768-ea95b100-7e46-11e9-8d1e-c67d21ede46e.gif)

**Comment by zhongqiang1839** [comment]
侧边栏宽度有对应的 media query。   做响应式的.

**Comment by happyhuizai** [comment]
找到原因了

![image](https://user-images.githubusercontent.com/29218617/58390319-4177d200-8063-11e9-8921-86f0396f491d.png)

当我把控制台往上拉的时候内容超出指定高度 `overflow-y`溢出了所以滚动出现了
跟`media query`没啥关系， 你的`media query`都是根据`width`做的,我没改变`width`

**Comment by zhongqiang1839** [comment]
> 找到原因了
> 
> ![image](https://user-images.githubusercontent.com/29218617/58390319-4177d200-8063-11e9-8921-86f0396f491d.png)
> 
> 当我把控制台往上拉的时候内容超出指定高度 `overflow-y`溢出了所以滚动出现了
> 跟`media query`没啥关系， 你的`media query`都是根据`width`做的,我没改变`width`


不错哦。滚动条出现占了一点宽度。
